[package]
name = "brave-flea-cli"
version = "0.1.0"
authors = ["Ted C. Howard <ted@tedchoward.com>"]
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }